default:
  client_id: YOUR_CLIENT_ID
  client_secret: YOUR_CLIENT_SECRET
  redirect_uri: http://localhost:3000/callback # To test subscription, deploy this code somewhere with a valid domain, replace redirect_uri with the domain/callback
  dialog_url: https://api.misfitwearables.com/auth/dialog/authorize
  exchange_url: https://api.misfitwearables.com/auth/tokens/exchange

development:

staging:

production:
